POST http://localhost:3001/api/blogs 
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNraWRzay5za29kc2tAZ21haWwuY29tIiwiaWQiOjIsImlhdCI6MTYzODg4NzMwNH0.Pl5sOe4eiElPT7ik3Ib9bt6rDNrVayk0MfDWCG0PpIg

{
    "title": "ploki", 
    "author": "Dr. Reactive", 
    "url": "www.netti.fi"
}